# Generated by Django 5.0.1 on 2024-02-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_ower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ower',
            new_name='owner',
        ),
    ]
