# Generated by Django 5.0.1 on 2024-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_ower_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
    ]
